DROP TABLE TBL_PESSOA, TBL_DOCENTE, TBL_DISCENTE;

CREATE TABLE TBL_PESSOA (
	id NUMERIC,
	name VARCHAR(50),
	cpf VARCHAR(50)
);

CREATE TABLE TBL_DOCENTE (
	dpto_id NUMERIC 
) INHERITS (TBL_PESSOA);

CREATE TABLE TBL_DISCENTE (
	course_id NUMERIC 
) INHERITS (TBL_PESSOA);



INSERT INTO TBL_DISCENTE (id, name, cpf, course_id) VALUES (1, 'Eduardo Reis Nobre', '05158724580', 1);

INSERT INTO TBL_DOCENTE (id, name, cpf, dpto_id) VALUES (2, 'MoHonda', '05158724580', 1);
